import { Inter } from "next/font/google";
import "./globals.css";
import Navebar from "@/components/Navebar";
import Footer from "@/components/Footer";
import Hero from "@/components/Hero";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Start Your Driving Journey",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="dark">
      <body className={inter.className}>
        <Navebar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
